name: borehole_app
description: A Flutter app for managing borehole data.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  sqflite_common_ffi: ^2.0.1
  file_picker: ^5.0.0
  csv: ^5.0.0
  google_maps_flutter: ^2.0.6
  path_provider: ^2.0.11
  intl: ^0.18.0
  permission_handler: ^10.2.0
  postgres: ^2.5.2 
  shared_preferences: ^2.0.15 
  fl_chart: ^0.69.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
